# Generated by Django 3.0 on 2021-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('descricao', models.TextField(max_length=350, verbose_name='Descricao')),
                ('anonimo', models.BooleanField(verbose_name='Anônimo')),
                ('voto_unico', models.BooleanField(verbose_name='Voto unico')),
                ('horario_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Horário de inicio da votação')),
                ('horario_termino', models.DateTimeField(blank=True, null=True, verbose_name='Horário do termino da votação')),
                ('horario_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Horário de criação')),
            ],
            options={
                'verbose_name': 'Votacao',
                'db_table': 'votacao',
            },
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa'},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=194, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='horario_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Horário de criação'),
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='pessoa',
        ),
    ]
