# Generated by Django 3.0 on 2021-03-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votacao',
            options={'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
        migrations.CreateModel(
            name='Opcao_voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('codigo_votacao', models.CharField(max_length=194, verbose_name='Codigo da votação ')),
                ('quantidade_votos', models.IntegerField(verbose_name='Quantidade de votos')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Votacao', verbose_name='Votação de participação')),
            ],
            options={
                'verbose_name': 'Opcão de voto',
                'verbose_name_plural': 'Opções de voto ',
                'db_table': 'Opcao_de_voto',
            },
        ),
    ]
